theme: jekyll-theme-architect
title: [Sensor Maestros Adesto Tech Serial Memory Driver/Demo GitPage]
description: [Sensor Maestros Adesto Tech Serial Memory Driver/Demo using Sensor Maestros smWSP and smMEM products]
show_downloads: ["contact Sensor Maestros for downloadable Zip file containing source code"]
